source 'https://rubygems.org'

gem 'rails'
gem 'rails-api'
gem 'rack-cors'

gem 'spring', :group => :development
gem 'sqlite3'

# To use ActiveModel has_secure_password
gem 'bcrypt'
gem 'has_secure_token'

# To use Jbuilder templates for JSON
gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
